//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShSzStockHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class DefaultUserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultUserSettings defaultInstance = ((DefaultUserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultUserSettings())));
        
        public static DefaultUserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ProductTheme {
            get {
                return ((int)(this["ProductTheme"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double ExcelCellFontSize {
            get {
                return ((double)(this["ExcelCellFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD3D3D3")]
        public global::System.Windows.Media.SolidColorBrush ExcelHeaderBackground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ExcelHeaderBackground"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft YaHei UI")]
        public string ExcelCellFontFamilyName {
            get {
                return ((string)(this["ExcelCellFontFamilyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy-M-d")]
        public string DateDisplayFormat {
            get {
                return ((string)(this["DateDisplayFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft YaHei UI")]
        public string DisplayFontFamilyName {
            get {
                return ((string)(this["DisplayFontFamilyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1990-12-01")]
        public global::System.DateTime MinDate {
            get {
                return ((global::System.DateTime)(this["MinDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StrikePriceSorting {
            get {
                return ((bool)(this["StrikePriceSorting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TotalVolumeSorting {
            get {
                return ((bool)(this["TotalVolumeSorting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DayVolumeSorting {
            get {
                return ((bool)(this["DayVolumeSorting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StrikePriceFiltering {
            get {
                return ((bool)(this["StrikePriceFiltering"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TotalVolumeFiltering {
            get {
                return ((bool)(this["TotalVolumeFiltering"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DayVolumeFiltering {
            get {
                return ((bool)(this["DayVolumeFiltering"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public decimal TotalVolumeUnit {
            get {
                return ((decimal)(this["TotalVolumeUnit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal DayVolumeUnit {
            get {
                return ((decimal)(this["DayVolumeUnit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TotalVolumeDecimalDigits {
            get {
                return ((int)(this["TotalVolumeDecimalDigits"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DayVolumeDecimalDigits {
            get {
                return ((int)(this["DayVolumeDecimalDigits"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ExcelFileFormat {
            get {
                return ((int)(this["ExcelFileFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0179FF")]
        public global::System.Windows.Media.SolidColorBrush ThemeColour_MaterialLight {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ThemeColour_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF05DAC5")]
        public global::System.Windows.Media.SolidColorBrush ThemeColour_MaterialDark {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ThemeColour_MaterialDark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF666666")]
        public global::System.Windows.Media.SolidColorBrush ContentTextColour_MaterialLight {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ContentTextColour_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF979797")]
        public global::System.Windows.Media.SolidColorBrush ContentTextColour_MaterialDark {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ContentTextColour_MaterialDark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../Images/MaterialLight/Menu.png")]
        public string MenuIconUri_MaterialLight {
            get {
                return ((string)(this["MenuIconUri_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../Images/MaterialDark/Menu.png")]
        public string MenuIconUri_MaterialDark {
            get {
                return ((string)(this["MenuIconUri_MaterialDark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/About.png")]
        public string AboutIconUri_MaterialLight {
            get {
                return ((string)(this["AboutIconUri_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialDark/About.png")]
        public string AboutIconUri_MaterialDark {
            get {
                return ((string)(this["AboutIconUri_MaterialDark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/ClearSelection.png")]
        public string ClearSelectionIconUri_MaterialLight {
            get {
                return ((string)(this["ClearSelectionIconUri_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialDark/ClearSelection.png")]
        public string ClearSelectionIconUri_MaterialDark {
            get {
                return ((string)(this["ClearSelectionIconUri_MaterialDark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/ExportToExcel.png")]
        public string ExportToExcelIconUri_MaterialLight {
            get {
                return ((string)(this["ExportToExcelIconUri_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialDark/ExportToExcel.png")]
        public string ExportToExcelIconUri_MaterialDark {
            get {
                return ((string)(this["ExportToExcelIconUri_MaterialDark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/Print.png")]
        public string PrintIconUri_MaterialLight {
            get {
                return ((string)(this["PrintIconUri_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialDark/Print.png")]
        public string PrintIconUri_MaterialDark {
            get {
                return ((string)(this["PrintIconUri_MaterialDark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/RestoreColumnWidth.png")]
        public string RestoreColumnWidthIconUri_MaterialLight {
            get {
                return ((string)(this["RestoreColumnWidthIconUri_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialDark/RestoreColumnWidth.png")]
        public string RestoreColumnWidthIconUri_MaterialDark {
            get {
                return ((string)(this["RestoreColumnWidthIconUri_MaterialDark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/Search.png")]
        public string SearchIconUri_MaterialLight {
            get {
                return ((string)(this["SearchIconUri_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialDark/Search.png")]
        public string SearchIconUri_MaterialDark {
            get {
                return ((string)(this["SearchIconUri_MaterialDark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DD000000")]
        public global::System.Windows.Media.SolidColorBrush PrimaryTextColour_MaterialLight {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["PrimaryTextColour_MaterialLight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DDFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush PrimaryTextColour_MaterialDark {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["PrimaryTextColour_MaterialDark"]));
            }
        }
    }
}
