//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShSzStockHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShSzStockHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沪深股票助手.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出到Excel.
        /// </summary>
        public static string ButtonExportToExcel_Label {
            get {
                return ResourceManager.GetString("ButtonExportToExcel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击搜索。.
        /// </summary>
        public static string ButtonSearch_ToolTip {
            get {
                return ResourceManager.GetString("ButtonSearch_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择结束日期（年-月-日）。.
        /// </summary>
        public static string DatePickerEndDate_ToolTip {
            get {
                return ResourceManager.GetString("DatePickerEndDate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束日期.
        /// </summary>
        public static string DatePickerEndDate_WaterMark {
            get {
                return ResourceManager.GetString("DatePickerEndDate_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择开始日期（年-月-日）。.
        /// </summary>
        public static string DatePickerStartDate_ToolTip {
            get {
                return ResourceManager.GetString("DatePickerStartDate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始日期.
        /// </summary>
        public static string DatePickerStartDate_WaterMark {
            get {
                return ResourceManager.GetString("DatePickerStartDate_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每日成交量（手）.
        /// </summary>
        public static string DayVolumeColumnHeader {
            get {
                return ResourceManager.GetString("DayVolumeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 97-2003 工作簿(*.xls)|*.xls|Excel 工作簿(*.xlsx)|*.xlsx.
        /// </summary>
        public static string SaveFileDialogueExportToExcel_Filter {
            get {
                return ResourceManager.GetString("SaveFileDialogueExportToExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成交价（元）.
        /// </summary>
        public static string StrikePriceColumnHeader {
            get {
                return ResourceManager.GetString("StrikePriceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未查询到数据！数据提供方反馈所查时间段过长。请您修改起止日期，两日期的间隔时长建议不超过9个月。.
        /// </summary>
        public static string TextBlockNullData_Text_ImproperDateRange {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_ImproperDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误。请提交反馈，以便帮助开发者优化用户体验。.
        /// </summary>
        public static string TextBlockNullData_Text_UnknownError {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未查询到数据！搜索条件有误，或数据提供方还没有更新数据。您可检查股票代码是否正确、所查时间段是否处于股市休市期。.
        /// </summary>
        public static string TextBlockNullData_Text_WrongFilters {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_WrongFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入股票代码，请以股票上市的交易所的代码开头（支持SH和SZ，大小写不限），之后接6位数字。.
        /// </summary>
        public static string TextBoxSymbol_ToolTip {
            get {
                return ResourceManager.GetString("TextBoxSymbol_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 股票代码.
        /// </summary>
        public static string TextBoxSymbol_WaterMark {
            get {
                return ResourceManager.GetString("TextBoxSymbol_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总成交量（手）.
        /// </summary>
        public static string TotalVolumeColumnHeader {
            get {
                return ResourceManager.GetString("TotalVolumeColumnHeader", resourceCulture);
            }
        }
    }
}
