//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShSzStockHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShSzStockHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string AlertDialogue_Title {
            get {
                return ResourceManager.GetString("AlertDialogue_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化中....
        /// </summary>
        public static string BusyIndicatorHomeWindowLoading_Header {
            get {
                return ResourceManager.GetString("BusyIndicatorHomeWindowLoading_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索中....
        /// </summary>
        public static string BusyIndicatorSearchResultArea_Header {
            get {
                return ResourceManager.GetString("BusyIndicatorSearchResultArea_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不了.
        /// </summary>
        public static string ButtonCancel_Label {
            get {
                return ResourceManager.GetString("ButtonCancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消选择的行.
        /// </summary>
        public static string ButtonClearSelection_Label {
            get {
                return ResourceManager.GetString("ButtonClearSelection_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是的.
        /// </summary>
        public static string ButtonOk_Label {
            get {
                return ResourceManager.GetString("ButtonOk_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印.
        /// </summary>
        public static string ButtonPrint_Label {
            get {
                return ResourceManager.GetString("ButtonPrint_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击打开打印预览，进行打印前的配置.
        /// </summary>
        public static string ButtonPrint_ToolTip {
            get {
                return ResourceManager.GetString("ButtonPrint_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还原列宽.
        /// </summary>
        public static string ButtonRestoreColumnWidth_Label {
            get {
                return ResourceManager.GetString("ButtonRestoreColumnWidth_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击搜索.
        /// </summary>
        public static string ButtonSearch_ToolTip {
            get {
                return ResourceManager.GetString("ButtonSearch_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选中.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ：.
        /// </summary>
        public static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yy年M月d日.
        /// </summary>
        public static string ComboBoxItem2Y1M1DCn_Content {
            get {
                return ResourceManager.GetString("ComboBoxItem2Y1M1DCn_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yy-M-d.
        /// </summary>
        public static string ComboBoxItem2Y1M1DHyphen_Content {
            get {
                return ResourceManager.GetString("ComboBoxItem2Y1M1DHyphen_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yy-MM-dd.
        /// </summary>
        public static string ComboBoxItem2Y2M2DHyphen_Content {
            get {
                return ResourceManager.GetString("ComboBoxItem2Y2M2DHyphen_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy年M月d日.
        /// </summary>
        public static string ComboBoxItem4Y1M1DCn_Content {
            get {
                return ResourceManager.GetString("ComboBoxItem4Y1M1DCn_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-M-d.
        /// </summary>
        public static string ComboBoxItem4Y1M1DHyphen_Content {
            get {
                return ResourceManager.GetString("ComboBoxItem4Y1M1DHyphen_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string ComboBoxItem4Y2M2DHyphen_Content {
            get {
                return ResourceManager.GetString("ComboBoxItem4Y2M2DHyphen_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string ComboBoxItemMaterialDark_Content {
            get {
                return ResourceManager.GetString("ComboBoxItemMaterialDark_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string ComboBoxItemMaterialLight_Content {
            get {
                return ResourceManager.GetString("ComboBoxItemMaterialLight_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 97-2003 工作簿（*.xls）.
        /// </summary>
        public static string ComboBoxItemXls_Content {
            get {
                return ResourceManager.GetString("ComboBoxItemXls_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 工作簿（*.xlsx）.
        /// </summary>
        public static string ComboBoxItemXlsx_Content {
            get {
                return ResourceManager.GetString("ComboBoxItemXlsx_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期格式.
        /// </summary>
        public static string DateDisplayFormatSetting {
            get {
                return ResourceManager.GetString("DateDisplayFormatSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签页标题、导出的Excel工作簿的默认文件名等之中的日期的显示格式。字母y代表年，M代表月，d代表日。字母的个数表示显示的数字的最小位数，必要时会以0补全。您对此设置的修改在已创建的标签页中可能不会完全生效，您可尝试再次搜索或创建新的标签页。.
        /// </summary>
        public static string DateDisplayFormatSetting_Explanation {
            get {
                return ResourceManager.GetString("DateDisplayFormatSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击日历图标来选择结束日期。除此之外，选择日期后，您也可以在输入框中编辑日期.
        /// </summary>
        public static string DatePickerEndDate_ToolTip {
            get {
                return ResourceManager.GetString("DatePickerEndDate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束日期.
        /// </summary>
        public static string DatePickerEndDate_WaterMark {
            get {
                return ResourceManager.GetString("DatePickerEndDate_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击日历图标来选择开始日期。除此之外，选择日期后，您也可以在输入框中编辑日期.
        /// </summary>
        public static string DatePickerStartDate_ToolTip {
            get {
                return ResourceManager.GetString("DatePickerStartDate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始日期.
        /// </summary>
        public static string DatePickerStartDate_WaterMark {
            get {
                return ResourceManager.GetString("DatePickerStartDate_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每日成交量.
        /// </summary>
        public static string DayVolume {
            get {
                return ResourceManager.GetString("DayVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认：.
        /// </summary>
        public static string DefaultSettingValue {
            get {
                return ResourceManager.GetString("DefaultSettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示字体.
        /// </summary>
        public static string DisplayFontFamilyNameSetting {
            get {
                return ResourceManager.GetString("DisplayFontFamilyNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 界面上的文字字体。只有您在弹出的应用重启确认对话框中确定重启此应用时，您对此设置的修改才会被保存，并在应用重启后生效。您对此设置的修改可能造成布局异常，若出现此问题，请您换用其他字体。.
        /// </summary>
        public static string DisplayFontFamilyNameSetting_Explanation {
            get {
                return ResourceManager.GetString("DisplayFontFamilyNameSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格字体.
        /// </summary>
        public static string ExcelCellFontFamilyNameSetting {
            get {
                return ResourceManager.GetString("ExcelCellFontFamilyNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出的Excel文件中数据区域单元格的文字字体。您对此设置的修改在已弹出的保存Excel文件对话框中不会生效，关闭对话框后再次导出到Excel可使之生效。.
        /// </summary>
        public static string ExcelCellFontFamilyNameSetting_Explanation {
            get {
                return ResourceManager.GetString("ExcelCellFontFamilyNameSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格字号.
        /// </summary>
        public static string ExcelCellFontSizeSetting {
            get {
                return ResourceManager.GetString("ExcelCellFontSizeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出的Excel文件中数据区域单元格的文字大小。建议保持默认值不变。您对此设置的修改在已弹出的保存Excel文件对话框中不会生效，关闭对话框后再次导出到Excel可使之生效。.
        /// </summary>
        public static string ExcelCellFontSizeSetting_Explanation {
            get {
                return ResourceManager.GetString("ExcelCellFontSizeSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件格式.
        /// </summary>
        public static string ExcelFileFormatSetting {
            get {
                return ResourceManager.GetString("ExcelFileFormatSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLS格式兼容性较好，若安装的Excel编辑软件版本较低，建议保存成此格式。此设置仅表示在保存Excel文件对话框中默认选择的文件格式，您依然能在对话框中更改文件格式。您对此设置的修改在已弹出的对话框中不会生效，关闭对话框后再次导出到Excel可使之生效。.
        /// </summary>
        public static string ExcelFileFormatSetting_Explanation {
            get {
                return ResourceManager.GetString("ExcelFileFormatSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出到Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 筛选.
        /// </summary>
        public static string FilteringSetting {
            get {
                return ResourceManager.GetString("FilteringSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列的筛选功能的开关。启用该功能允许您设定条件来显示符合的数据。您对此设置中关于.
        /// </summary>
        public static string FilteringSetting_Explanation {
            get {
                return ResourceManager.GetString("FilteringSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 五.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （.
        /// </summary>
        public static string LeftBracket {
            get {
                return ResourceManager.GetString("LeftBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最早日期.
        /// </summary>
        public static string MinDateSetting {
            get {
                return ResourceManager.GetString("MinDateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期选择框中允许选择的最早日期。上海证券交易所在1990年12月19日开始正式营业，深圳证券交易所则在1990年12月1日开始营业。由于数据提供方并不是从营业开始记录数据，您可通过点击日历图标或直接在输入框中编辑来适当修改此项设置。.
        /// </summary>
        public static string MinDateSetting_Explanation {
            get {
                return ResourceManager.GetString("MinDateSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （未知版权声明）.
        /// </summary>
        public static string NullProductCopyrightError {
            get {
                return ResourceManager.GetString("NullProductCopyrightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （未知程序名）.
        /// </summary>
        public static string NullProductNameError {
            get {
                return ResourceManager.GetString("NullProductNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （未知版本号）.
        /// </summary>
        public static string NullProductVersionError {
            get {
                return ResourceManager.GetString("NullProductVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元.
        /// </summary>
        public static string PriceUnit {
            get {
                return ResourceManager.GetString("PriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印预览.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ？.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ）.
        /// </summary>
        public static string RightBracket {
            get {
                return ResourceManager.GetString("RightBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 六.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 97-2003 工作簿(*.xls)|*.xls|Excel 工作簿(*.xlsx)|*.xlsx.
        /// </summary>
        public static string SaveFileDialogueExportToExcel_Filter {
            get {
                return ResourceManager.GetString("SaveFileDialogueExportToExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        public static string SortingSetting {
            get {
                return ResourceManager.GetString("SortingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列的排序功能的开关。启用该功能允许您对数据进行升序或降序排列。您对此设置中关于.
        /// </summary>
        public static string SortingSetting_Explanation {
            get {
                return ResourceManager.GetString("SortingSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成交价.
        /// </summary>
        public static string StrikePrice {
            get {
                return ResourceManager.GetString("StrikePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新标签页.
        /// </summary>
        public static string TabItemStrikePriceVolume_Header_NewTab {
            get {
                return ResourceManager.GetString("TabItemStrikePriceVolume_Header_NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 的列的部分的修改在已显示的表格中不会生效，再次搜索可使之生效。.
        /// </summary>
        public static string TableColumnSettings_Explanation {
            get {
                return ResourceManager.GetString("TableColumnSettings_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格.
        /// </summary>
        public static string TableSettings {
            get {
                return ResourceManager.GetString("TableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 的修改需要重启此应用，已创建的标签页会被关闭。若您确定重启此应用，您对此设置的修改将会被保存，并在应用重启后生效。您确定重启此应用吗？.
        /// </summary>
        public static string TextBlockAppRestartAlert_Text {
            get {
                return ResourceManager.GetString("TextBlockAppRestartAlert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击左上方的“+”按钮新建标签页，开始搜索吧！.
        /// </summary>
        public static string TextBlockNewTabHint_Text {
            get {
                return ResourceManager.GetString("TextBlockNewTabHint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未查询到数据！数据提供方拒绝访问，解封一般需要5~60分钟。因数据提供方限制，请您降低搜索频率，并建议您起止日期的间隔时长不超过1个月。.
        /// </summary>
        public static string TextBlockNullData_Text_AccessDenied {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询未全部完成！数据提供方拒绝了部分访问，解封一般需要5~60分钟。因数据提供方限制，请您降低搜索频率，并建议您起止日期的间隔时长不超过1个月。.
        /// </summary>
        public static string TextBlockNullData_Text_AccessDeniedPartially {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_AccessDeniedPartially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未查询到数据！数据提供方反馈所查时间段过长。请您修改起止日期，两日期的间隔时长建议不超过1个月，最长不应超过9个月。.
        /// </summary>
        public static string TextBlockNullData_Text_ImproperDateRange {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_ImproperDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未查询到数据！请检查您的网络连接状况。.
        /// </summary>
        public static string TextBlockNullData_Text_NetworkError {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误。请提交反馈，以便帮助开发者优化用户体验。.
        /// </summary>
        public static string TextBlockNullData_Text_UnknownError {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未查询到数据！搜索条件有误，或数据提供方没有相关数据。您可检查股票所属公司上市状态、股票代码是否正确、所查时间段是否处于股市休市期。.
        /// </summary>
        public static string TextBlockNullData_Text_WrongFilters {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_WrongFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在使用.
        /// </summary>
        public static string TextBlockOpenSource_Text_Part1 {
            get {
                return ResourceManager.GetString("TextBlockOpenSource_Text_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此开源软件.
        /// </summary>
        public static string TextBlockOpenSource_Text_Part2 {
            get {
                return ResourceManager.GetString("TextBlockOpenSource_Text_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时，请遵守相关许可协议。.
        /// </summary>
        public static string TextBlockOpenSource_Text_Part3 {
            get {
                return ResourceManager.GetString("TextBlockOpenSource_Text_Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 股票代码应以上市交易所代码开头（支持SH和SZ，大小写不限）接6位数字。股票名称在输入框失去焦点后会自动转换成对应的代码（如果有）.
        /// </summary>
        public static string TextBoxSymbol_ToolTip {
            get {
                return ResourceManager.GetString("TextBoxSymbol_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 股票代码.
        /// </summary>
        public static string TextBoxSymbol_WaterMark {
            get {
                return ResourceManager.GetString("TextBoxSymbol_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string ThemeSetting {
            get {
                return ResourceManager.GetString("ThemeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 界面主题风格。只有您在弹出的应用重启确认对话框中确定重启此应用时，您对此设置的修改才会被保存，并在应用重启后生效。.
        /// </summary>
        public static string ThemeSetting_Explanation {
            get {
                return ResourceManager.GetString("ThemeSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四.
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总成交量.
        /// </summary>
        public static string TotalVolume {
            get {
                return ResourceManager.GetString("TotalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不选中.
        /// </summary>
        public static string Unchecked {
            get {
                return ResourceManager.GetString("Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成交量小数位数.
        /// </summary>
        public static string VolumeDecimalDigitsSetting {
            get {
                return ResourceManager.GetString("VolumeDecimalDigitsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总成交量和每日成交量保留的小数位数。若需要显示准确值，数据在不同单位需要保留的小数位数不同，这由手和股的换算关系决定。数据的小数部分在必要时会用0补齐。您对此设置的修改在已显示的表格中不会生效，再次搜索可使之生效。.
        /// </summary>
        public static string VolumeDecimalDigitsSetting_Explanation {
            get {
                return ResourceManager.GetString("VolumeDecimalDigitsSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手.
        /// </summary>
        public static string VolumeUnit_1 {
            get {
                return ResourceManager.GetString("VolumeUnit_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十手.
        /// </summary>
        public static string VolumeUnit_10 {
            get {
                return ResourceManager.GetString("VolumeUnit_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 百手.
        /// </summary>
        public static string VolumeUnit_100 {
            get {
                return ResourceManager.GetString("VolumeUnit_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千手.
        /// </summary>
        public static string VolumeUnit_1000 {
            get {
                return ResourceManager.GetString("VolumeUnit_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 万手.
        /// </summary>
        public static string VolumeUnit_10000 {
            get {
                return ResourceManager.GetString("VolumeUnit_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成交量单位.
        /// </summary>
        public static string VolumeUnitSetting {
            get {
                return ResourceManager.GetString("VolumeUnitSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总成交量和每日成交量的单位。1手等于100股。您对此设置的修改在已显示的表格中不会生效，再次搜索可使之生效。.
        /// </summary>
        public static string VolumeUnitSetting_Explanation {
            get {
                return ResourceManager.GetString("VolumeUnitSetting_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
    }
}
