//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShSzStockHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShSzStockHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索中....
        /// </summary>
        public static string BusyIndicator_Header {
            get {
                return ResourceManager.GetString("BusyIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消选择的行.
        /// </summary>
        public static string ButtonClearSelection_Label {
            get {
                return ResourceManager.GetString("ButtonClearSelection_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出到Excel.
        /// </summary>
        public static string ButtonExportToExcel_Label {
            get {
                return ResourceManager.GetString("ButtonExportToExcel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印.
        /// </summary>
        public static string ButtonPrint_Label {
            get {
                return ResourceManager.GetString("ButtonPrint_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击打开打印预览，进行打印前的配置.
        /// </summary>
        public static string ButtonPrint_ToolTip {
            get {
                return ResourceManager.GetString("ButtonPrint_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击搜索.
        /// </summary>
        public static string ButtonSearch_ToolTip {
            get {
                return ResourceManager.GetString("ButtonSearch_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择结束日期（年-月-日）.
        /// </summary>
        public static string DatePickerEndDate_ToolTip {
            get {
                return ResourceManager.GetString("DatePickerEndDate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束日期.
        /// </summary>
        public static string DatePickerEndDate_WaterMark {
            get {
                return ResourceManager.GetString("DatePickerEndDate_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择开始日期（年-月-日）.
        /// </summary>
        public static string DatePickerStartDate_ToolTip {
            get {
                return ResourceManager.GetString("DatePickerStartDate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始日期.
        /// </summary>
        public static string DatePickerStartDate_WaterMark {
            get {
                return ResourceManager.GetString("DatePickerStartDate_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每日成交量.
        /// </summary>
        public static string DayVolume {
            get {
                return ResourceManager.GetString("DayVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 五.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （.
        /// </summary>
        public static string LeftBracket {
            get {
                return ResourceManager.GetString("LeftBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元.
        /// </summary>
        public static string PriceUnit {
            get {
                return ResourceManager.GetString("PriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ？.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ）.
        /// </summary>
        public static string RightBracket {
            get {
                return ResourceManager.GetString("RightBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 六.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 97-2003 工作簿(*.xls)|*.xls|Excel 工作簿(*.xlsx)|*.xlsx.
        /// </summary>
        public static string SaveFileDialogueExportToExcel_Filter {
            get {
                return ResourceManager.GetString("SaveFileDialogueExportToExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成交价.
        /// </summary>
        public static string StrikePrice {
            get {
                return ResourceManager.GetString("StrikePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未查询到数据！数据提供方拒绝了您的访问，解封一般需要您等待5~60分钟。这可能是因为您搜索频率过高。请您降低搜索频率，并建议您起止日期的间隔时长不超过1个月。.
        /// </summary>
        public static string TextBlockNullData_Text_AccessDenied {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未查询到数据！数据提供方反馈所查时间段过长。请您修改起止日期，两日期的间隔时长建议不超过1个月，最长不应超过9个月。.
        /// </summary>
        public static string TextBlockNullData_Text_ImproperDateRange {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_ImproperDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误。请提交反馈，以便帮助开发者优化用户体验。.
        /// </summary>
        public static string TextBlockNullData_Text_UnknownError {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未查询到数据！搜索条件有误，或数据提供方还没有更新数据。您可检查股票代码是否正确、所查时间段是否处于股市休市期。.
        /// </summary>
        public static string TextBlockNullData_Text_WrongFilters {
            get {
                return ResourceManager.GetString("TextBlockNullData_Text_WrongFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入股票代码，请以股票上市的交易所的代码开头（支持SH和SZ，大小写不限），之后接6位数字.
        /// </summary>
        public static string TextBoxSymbol_ToolTip {
            get {
                return ResourceManager.GetString("TextBoxSymbol_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 股票代码.
        /// </summary>
        public static string TextBoxSymbol_WaterMark {
            get {
                return ResourceManager.GetString("TextBoxSymbol_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四.
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总成交量.
        /// </summary>
        public static string TotalVolume {
            get {
                return ResourceManager.GetString("TotalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手.
        /// </summary>
        public static string VolumeUnit_1 {
            get {
                return ResourceManager.GetString("VolumeUnit_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 万手.
        /// </summary>
        public static string VolumeUnit_10000 {
            get {
                return ResourceManager.GetString("VolumeUnit_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
    }
}
