//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShSzStockHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft YaHei UI")]
        public string DisplayFontFamilyName {
            get {
                return ((string)(this["DisplayFontFamilyName"]));
            }
            set {
                this["DisplayFontFamilyName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double PrimaryTextFontSize {
            get {
                return ((double)(this["PrimaryTextFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double ContentTextFontSize {
            get {
                return ((double)(this["ContentTextFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.SolidColorBrush ColourDanger {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ColourDanger"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD3D3D3")]
        public global::System.Windows.Media.SolidColorBrush ExcelHeaderBackground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ExcelHeaderBackground"]));
            }
            set {
                this["ExcelHeaderBackground"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double MaxCellWidth {
            get {
                return ((double)(this["MaxCellWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double MinCellWidth {
            get {
                return ((double)(this["MinCellWidth"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double ExcelCellFontSize {
            get {
                return ((double)(this["ExcelCellFontSize"]));
            }
            set {
                this["ExcelCellFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft YaHei UI")]
        public string ExcelCellFontFamilyName {
            get {
                return ((string)(this["ExcelCellFontFamilyName"]));
            }
            set {
                this["ExcelCellFontFamilyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy-M-d")]
        public string DateDisplayFormat {
            get {
                return ((string)(this["DateDisplayFormat"]));
            }
            set {
                this["DateDisplayFormat"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy-M-d")]
        public string DateCodeFormat {
            get {
                return ((string)(this["DateCodeFormat"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1990-12-01")]
        public global::System.DateTime MinDate {
            get {
                return ((global::System.DateTime)(this["MinDate"]));
            }
            set {
                this["MinDate"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double HugeIconSideLength {
            get {
                return ((double)(this["HugeIconSideLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public double SmallIconSideLength {
            get {
                return ((double)(this["SmallIconSideLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double MaxTabItemWidth {
            get {
                return ((double)(this["MaxTabItemWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double MaxDropDownHeight {
            get {
                return ((double)(this["MaxDropDownHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int MaxInputLength {
            get {
                return ((int)(this["MaxInputLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double DefaultWindowHeight {
            get {
                return ((double)(this["DefaultWindowHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double DefaultWindowWidth {
            get {
                return ((double)(this["DefaultWindowWidth"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ProductTheme {
            get {
                return ((int)(this["ProductTheme"]));
            }
            set {
                this["ProductTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF666666")]
        public global::System.Windows.Media.SolidColorBrush ContentTextColour {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ContentTextColour"]));
            }
            set {
                this["ContentTextColour"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF999999")]
        public global::System.Windows.Media.SolidColorBrush ExplanationTextColour {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ExplanationTextColour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double ExplanationTextFontSize {
            get {
                return ((double)(this["ExplanationTextFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public double HugeTextFontSize {
            get {
                return ((double)(this["HugeTextFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double SmallWindowHeight {
            get {
                return ((double)(this["SmallWindowHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public string SmallWindowWidth {
            get {
                return ((string)(this["SmallWindowWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public double DataGridHeaderRowHeight {
            get {
                return ((double)(this["DataGridHeaderRowHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public double TitleTextFontSize {
            get {
                return ((double)(this["TitleTextFontSize"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0179FF")]
        public global::System.Windows.Media.SolidColorBrush ThemeColour {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ThemeColour"]));
            }
            set {
                this["ThemeColour"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zh-CN")]
        public string CultureInfo {
            get {
                return ((string)(this["CultureInfo"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StrikePriceSorting {
            get {
                return ((bool)(this["StrikePriceSorting"]));
            }
            set {
                this["StrikePriceSorting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TotalVolumeSorting {
            get {
                return ((bool)(this["TotalVolumeSorting"]));
            }
            set {
                this["TotalVolumeSorting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DayVolumeSorting {
            get {
                return ((bool)(this["DayVolumeSorting"]));
            }
            set {
                this["DayVolumeSorting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StrikePriceFiltering {
            get {
                return ((bool)(this["StrikePriceFiltering"]));
            }
            set {
                this["StrikePriceFiltering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TotalVolumeFiltering {
            get {
                return ((bool)(this["TotalVolumeFiltering"]));
            }
            set {
                this["TotalVolumeFiltering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DayVolumeFiltering {
            get {
                return ((bool)(this["DayVolumeFiltering"]));
            }
            set {
                this["DayVolumeFiltering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public decimal TotalVolumeUnit {
            get {
                return ((decimal)(this["TotalVolumeUnit"]));
            }
            set {
                this["TotalVolumeUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal DayVolumeUnit {
            get {
                return ((decimal)(this["DayVolumeUnit"]));
            }
            set {
                this["DayVolumeUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TotalVolumeDecimalDigits {
            get {
                return ((int)(this["TotalVolumeDecimalDigits"]));
            }
            set {
                this["TotalVolumeDecimalDigits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DayVolumeDecimalDigits {
            get {
                return ((int)(this["DayVolumeDecimalDigits"]));
            }
            set {
                this["DayVolumeDecimalDigits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ExcelFileFormat {
            get {
                return ((int)(this["ExcelFileFormat"]));
            }
            set {
                this["ExcelFileFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../Images/MaterialLight/Menu.png")]
        public string MenuIconUri {
            get {
                return ((string)(this["MenuIconUri"]));
            }
            set {
                this["MenuIconUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/About.png")]
        public string AboutIconUri {
            get {
                return ((string)(this["AboutIconUri"]));
            }
            set {
                this["AboutIconUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/ClearSelection.png")]
        public string ClearSelectionIconUri {
            get {
                return ((string)(this["ClearSelectionIconUri"]));
            }
            set {
                this["ClearSelectionIconUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/ExportToExcel.png")]
        public string ExportToExcelIconUri {
            get {
                return ((string)(this["ExportToExcelIconUri"]));
            }
            set {
                this["ExportToExcelIconUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/Print.png")]
        public string PrintIconUri {
            get {
                return ((string)(this["PrintIconUri"]));
            }
            set {
                this["PrintIconUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/ExportToExcel.png")]
        public string RestoreColumnWidthIconUri {
            get {
                return ((string)(this["RestoreColumnWidthIconUri"]));
            }
            set {
                this["RestoreColumnWidthIconUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../Images/MaterialLight/Search.png")]
        public string SearchIconUri {
            get {
                return ((string)(this["SearchIconUri"]));
            }
            set {
                this["SearchIconUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DD000000")]
        public global::System.Windows.Media.SolidColorBrush PrimaryTextColour {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["PrimaryTextColour"]));
            }
            set {
                this["PrimaryTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double MediumIconSideLength {
            get {
                return ((double)(this["MediumIconSideLength"]));
            }
            set {
                this["MediumIconSideLength"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double TitleBarButtonSideLength {
            get {
                return ((double)(this["TitleBarButtonSideLength"]));
            }
        }
    }
}
